name: "tiktok"
mode: "dev"
port: 8000
version: "v0.0.1"
start_time: "2023-01-25"
machine_id: 1

auth:
  jwt_secret: "jwt-tiktok"
  jwt_expire: 86400

log:
  level: "info"
  filename: "./log/tiktok.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5
  gorm_slowthreshold: 1000 # ms单位

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "666666"
  dbname: "tiktok"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
